export const USER_ACTION_TYPES = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT'
}

export const SERVICE_ACTION_TYPES = {
  FETCH_SERVICES_REQUEST: 'FETCH_SERVICES_REQUEST',
  FETCH_SERVICES_SUCCESS: 'FETCH_SERVICES_SUCCESS',
  FETCH_SERVICES_FAILURE: 'FETCH_SERVICES_FAILURE',
  FETCH_SERVICE_DETAIL_REQUEST: 'FETCH_SERVICE_DETAIL_REQUEST',
  FETCH_SERVICE_DETAIL_SUCCESS: 'FETCH_SERVICE_DETAIL_SUCCESS',
  FETCH_MASTERS_REQUEST: 'FETCH_MASTERS_REQUEST',
  FETCH_MASTERS_SUCCESS: 'FETCH_MASTERS_SUCCESS',
  SET_CITY: 'SET_CITY'
}

export const ORDER_ACTION_TYPES = {
  FETCH_ORDERS_REQUEST: 'FETCH_ORDERS_REQUEST',
  FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
  FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE',
  CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',
  UPDATE_ORDER_STATUS: 'UPDATE_ORDER_STATUS',
  FETCH_CONTACTS_REQUEST: 'FETCH_CONTACTS_REQUEST',
  FETCH_CONTACTS_SUCCESS: 'FETCH_CONTACTS_SUCCESS',
  ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS'
}
